apiVersion: v1
kind: ConfigMap
metadata:
  name: companies-filter-config
data:
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_EXCHANGE: "events"
  RABBITMQ_ROUTING_KEYS: "companies,arso"
  USERS_SERVICE_URL: "http://users:80/graphql"
  COMPANIES_SYNC_URL: "http://companies:80"
  ARSO_SYNC_URL: "http://arso-service:80"