apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-filter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companies-filter
  template:
    metadata:
      labels:
        app: companies-filter
    spec:
      containers:
        - name: companies-filter
          image: zln00/companies-filter:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: companies-filter-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10