apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-filter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companies-filter
  template:
    metadata:
      labels:
        app: companies-filter
    spec:
      containers:
        - name: companies-filter
          image: zln00/companies-filter:latest
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_EXCHANGE
              value: "events"
            - name: RABBITMQ_ROUTING_KEYS
              value: "companies,arso"
            - name: USERS_SERVICE_URL
              value: "http://users:80/graphql"
            - name: COMPANIES_SYNC_URL
              value: "http://companies:80"
            - name: ARSO_SYNC_URL
              value: "http://arso-service:80"

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10