apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: companies-filter
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`companies-filter.localhost`)
      kind: Rule
      services:
        - name: companies-filter
          port: 9000
