apiVersion: v1
kind: ConfigMap
metadata:
  name: arso-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "arso"
  DB_USER: "arso_user"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_EXCHANGE: "events"
  RABBITMQ_ROUTING_KEY: "arso"