apiVersion: batch/v1
kind: CronJob
metadata:
  name: arso-sync
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
      spec:
        template:
          metadata:
            labels:
              app: arso-sync
          spec:
            containers:
            - name: arso-sync
              image: zln00/arso-sync:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: arso-config
              env:
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
            restartPolicy: OnFailure