apiVersion: batch/v1
kind: CronJob
metadata:
  name: companies-sync
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: companies-sync
        spec:
          containers:
            - name: companies-sync
              image: companies-sync:local
              imagePullPolicy: IfNotPresent
              env:
                - name: DB_HOST
                  value: "postgres-companies"
                - name: DB_PORT
                  value: "5432"
                - name: DB_NAME
                  value: "companies"
                - name: DB_USER
                  value: "companies_user"
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
          restartPolicy: OnFailure