apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-companies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-companies
  template:
    metadata:
      labels:
        app: postgres-companies
    spec:
      containers:
        - name: postgres-companies
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-companies-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-companies-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "companies_user", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "companies_user", "-h", "localhost"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
      volumes:
        - name: postgres-companies-data
          persistentVolumeClaim:
            claimName: postgres-companies-pvc