apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: users-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`localhost`) && PathPrefix(`/users`)
      kind: Rule
      services:
        - name: users
          port: 8000
