apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: users
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`users.localhost`)
      kind: Rule
      services:
        - name: users
          port: 80